workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials
        - FIREBASE_TOKEN
        - other
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up key.properties
        echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
        cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
        - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - flutter packages pub get
        - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - medoleader91@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:1033037829777:android:98359919d7630e78bf1130
          groups:
            - androidTesters

