workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: "io.codemagic.ahmedapp"
      groups:
        - keystore_credentials
        - FIREBASE_TOKEN
        - other
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build Android
        script: |
              echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
              cd android && bash ./gradlew assembleRelease
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release --build-name=1.0.5 --build-number=1.0.5 --package-name "$PACKAGE_NAME"
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
          - medoleader91@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:1033037829777:android:98359919d7630e78bf1130
          groups:
            - androidTesters

