workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials
        - FIREBASE_TOKEN
        - other
      flutter: stable
    scripts:
      - name: Set up key.properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$FCI_BUILD_DIR/project_directory/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Set up local.properties
        script: |
            echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release --build-name=1.0.5
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
          - medoleader91@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:1033037829777:android:98359919d7630e78bf1130
          groups:
            - androidTesters

