workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    max_build_duration: 120
    environment:
      groups:
        - keystore_credentials
        - FIREBASE_TOKEN
        - other
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build Android
        script: |
              echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
              cd android && bash ./gradlew assembleRelease
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release --build-name=1.0.5 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME")))
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
          - medoleader91@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_token: 1//03q1CL34HYY_0CgYIARAAGAMSNwF-L9Irloyj2pDB3M9X91wZw5GycgCZmbIQQgrOnIKXIc5MgKy4rVljulTGgWytSVTgUkAgtYc
        android:
          app_id: 1:1033037829777:android:98359919d7630e78bf1130
          groups:
            - androidTesters

